version: 0.2

env:
  variables:
    JAVA_HOME: "/usr/lib/jvm/java-17-amazon-corretto/"
phases:
  install:
    commands:
      - apt update
      - apt install -y java-17-amazon-corretto-jdk
      - update-alternatives --auto javac
      - update-alternatives --auto java
  build:
    commands:
      - echo Build Starting on `date`
      - chmod +x ./gradlew
      - ./gradlew build
  post_build:
    commands:
      - echo $(basename ./build/libs/*.jar)
artifacts:
  files:
    - build/libs/*.jar
    - scripts/**
    - appspec.yml
  discard-paths: yes