#spring.datasource.url=jdbc:h2:mem:testdb
spring:
  thymeleaf:
    cache: false
  thymeleaf3:
    decoupled-logic: true
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000
  h2:
    console:
      enabled: false
  datasource:
#    url: jdbc:mysql://localhost:3306/lineup
#    url: jdbc:mysql://zulseoza-db.c3tfzg21eqej.ap-northeast-2.rds.amazonaws.com:13306/zulseoza?useSSL=false&characterEncoding=UTP-8&serverTimezone=UTC
#    username: ${LINEUP_DB_ID}
#    password: ${LINEUP_DB_PW}
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always

  data:
    rest:
      base-path: /api
      detection-strategy: annotated
  devtools:
    restart:
      quiet-period: 700ms
      enabled: true
    livereload:
      enabled: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 96781809157-5ek215a9ggvq3tuhpnc7r5o1tsukg1pd.apps.googleusercontent.com
          kakao:
            client-id: 535d186fd8ce43114bfa72ded42ffc58

debug: false
#management:
#  endpoints:
#    web:
#      exposure:
#        include:
server:
  error:
    whitelabel:
      enabled: false

logging.level:
  org:
    hibernate:
      type:
        descriptor:
          sql:
            org.hibernate.type.descriptor.sql.BasicBinder : trace
    springframework:
      web.servlet : debug